---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-elbv2-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - elbv2.services.k8s.aws
  resources:
  - listeners
  - loadbalancers
  verbs:
  - get
  - list
  - watch
